<form id="frm_postdata" name="frm_postdata" enctype="multipart/form-data" method="POST">
	<input type="hidden" name="currentPage" id="currentPage" size="6" maxlength="6" value="<?php echo $this->numPage;?>" class="inputbox2 narrowkey1"></input>
		<?php 
			$seq = substr($this->seq,1,4);
			$seq += 1;
			$seq=str_pad($seq, 4, '0', STR_PAD_LEFT);
			$seq='S'.$seq;
		?>
		<div class="panel">
            <fieldset class="panel-dt">							
				<h4><i class="fa fa-angle-right"></i> Tambah Supplier</h4>
						<br>
					<div class="col-sm-12">
						<table width="100%">
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Kode Supplier</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="kode_supplier" id="kode_supplier" type="text" maxlength="50" size="5" class="form-control input-sm" value="<?php echo $seq;?>" readonly> </td>
										<td> </td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Nama Supplier</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="nama_supplier" id="nama_supplier" type="text" maxlength="50" size="50" class="form-control input-sm"> </td>
										<td> &nbsp; <label id="nama_supplier-error" for="nama_supplier" class="error"></label> </td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Alamat</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="alamat_supplier" id="alamat_supplier" type="text" maxlength="100" size="100" class="form-control input-sm" value=""> </td>
										<td> &nbsp; <label id="alamat_supplier-error" for="alamat_supplier" class="error"></td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Nomor Tlp</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="no_tlp" id="no_tlp" type="text" maxlength="50" size="20" class="form-control input-sm" value=""> </td>
										<td> &nbsp; <label id="no_tlp-error" for="no_tlp" class="error"></td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Nomor HP/WA</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="no_hp" id="no_hp" type="text" maxlength="50" size="20" class="form-control input-sm" value="" onkeypress="javascript:return isNumber(event)"> </td>
										<td> &nbsp; <label id="no_hp-error" for="no_hp" class="error"></td>
									</table>
								</td>
							</tr> 
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Email</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> <input name="email" id="email" type="text" maxlength="50" size="50" class="form-control input-sm" value=""> </td>
										<td> &nbsp; <label id="email-error" for="email" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Tipe</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> 
											<select id="tipe" name="tipe" class = "form-control input-sm" width="15%">
												<option value="0">--Pilih Tipe--</option>
												<option value="Lokal">Lokal</option>
												<option value="Impor">Impor</option>
												<option value="Konsinyasi">Konsinyasi</option>
											</select>
										</td>
										<td> &nbsp; <label id="tipe-error" for="tipe" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td width="10%"><font style="font-size:12px;font-weight:bold;">Status</font></td>
								<td width="1%">:</td>
								<td>
									<table>
										<td> 
											<select id="status" name="status" class = "form-control input-sm" width="15%">
												<option value="">--Pilih Status--</option>
												<option value="1">Active</option>
												<option value="0">Inactive</option>
											</select>
										</td>
										<td> &nbsp; <label id="status-error" for="status" class="error"></td>
									</table>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
						</table>
					</div>				
			</fieldset>
		</div>
		
	</div>
</div>
<div class="col-lg-12">
<div class="form-group form-group-bottom" align="right">
						<input type="hidden" id="proses" name="proses" value="<?php echo $this->proses?>">	
						<br><br>
							
							<a href="supplier">
							<button type="button" class="btn btn-theme02">
								<span class="fa fa-backward"></span> &nbsp;Kembali
							</button></a>
							<button type="button" class="btn btn-theme03" onCLick="PostData()">
								<span class="fa fa-save"></span> &nbsp;Simpan
							</button>
							
			</div>
</div>
</form>
  <script src="<?php echo $this->baseUrl();?>/lib/jquery/jquery.min.js"></script>
  <script src="<?php echo $this->baseUrl();?>/lib/bootstrap/js/bootstrap.min.js"></script>
  <script src="<?php echo $this->baseUrl();?>/lib/jquery.form.js"></script>
  <script src="<?php echo $this->baseUrl();?>/lib/jquery.scrollTo.min.js"></script>
  <script src="<?php echo $this->baseUrl();?>/lib/jquery.nicescroll.js" type="text/javascript"></script>
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/sweetalert.css">
  <script src="<?php echo $this->baseUrl();?>/lib/sweetalert.min.js"></script>
<script>
	function PostData()
    {
		var nama_supplier 	  = $('[name="nama_supplier"]').val();
		var alamat_supplier   = $('[name="alamat_supplier"]').val();
		var no_tlp 		  	  = $('[name="no_tlp"]').val();
		var no_hp 			  = $('#no_hp').val();
		var email 			  = $('[name="email"]').val();
		var tipe 			  = $('[name="tipe"]').val()
		var status 			  = $('[name="status"]').val();
		var kode_supplier 			  = $('[name="kode_supplier"]').val();
		var atps			  = email.indexOf("@");
		var dots			  = email.lastIndexOf(".");
			
	 
		if (nama_supplier=="") {
			document.getElementById('nama_supplier-error').innerHTML ="<span style='color: red;'>Nama Supplier Harus Diisi.</span>";
			document.getElementById('nama_supplier').focus();
				 
	    }else if (alamat_supplier=="") {
			document.getElementById('alamat_supplier-error').innerHTML ="<span style='color: red;'>Alamat Supplier Harus Diisi.</span>";
			document.getElementById('alamat_supplier').focus();
			document.getElementById('nama_supplier-error').innerHTML ='';
	    }else if (no_tlp=="") {
		    document.getElementById('no_tlp-error').innerHTML ="<span style='color: red;'>Nomor Tlp Harus Diisi.</span>";
			document.getElementById('no_tlp').focus();
			document.getElementById('alamat_supplier-error').innerHTML ='';
			document.getElementById('nama_supplier').focus();
		 }else if (no_hp=="") {
			document.getElementById('no_hp-error').innerHTML ="<span style='color: red;'>Nomor HP Harus Diisi.</span>";
			document.getElementById('no_hp').focus();
			document.getElementById('no_tlp-error').innerHTML ='';
			document.getElementById('alamat_supplier-error').innerHTML ='';
	 
		}else if (email=="") {
			document.getElementById('email-error').innerHTML ="<span style='color: red;'>Email Harus Diisi.</span>";
			document.getElementById('email').focus();
			document.getElementById('no_hp-error').innerHTML ='';
			document.getElementById('no_tlp-error').innerHTML ='';
			document.getElementById('alamat_supplier-error').innerHTML ='';	 
		}else if (atps<1 || dots<atps+2 || dots+2>=email.length) {
			document.getElementById('email-error').innerHTML ="<span style='color: red;'>Alamat email tidak valid.</span>";
			document.getElementById('email').focus();

		 
			document.getElementById('no_hp-error').innerHTML ='';
			document.getElementById('no_tlp-error').innerHTML ='';
			document.getElementById('alamat_supplier-error').innerHTML ='';
		}else if (tipe == '0') {
			document.getElementById('tipe-error').innerHTML ="<span style='color: red;'>Tipe Harus Dipilih.</span>";
			document.getElementById('tipe').focus();	 
			document.getElementById('email-error').innerHTML ='';
			document.getElementById('no_hp-error').innerHTML ='';
			document.getElementById('no_tlp-error').innerHTML ='';
			document.getElementById('alamat_supplier-error').innerHTML ='';
		}else if (status == '') {
			document.getElementById('status-error').innerHTML ="<span style='color: red;'>status Harus Dipilih.</span>";
			document.getElementById('status').focus();
			document.getElementById('tipe-error').innerHTML ='';
			document.getElementById('email-error').innerHTML ='';
			document.getElementById('no_hp-error').innerHTML ='';
			document.getElementById('no_tlp-error').innerHTML ='';
			document.getElementById('alamat_supplier-error').innerHTML ='';
		}else{
			document.getElementById('status-error').innerHTML ='';
			document.getElementById('tipe-error').innerHTML ='';
			document.getElementById('email-error').innerHTML ='';
			document.getElementById('no_hp-error').innerHTML ='';
			document.getElementById('no_tlp-error').innerHTML ='';
			document.getElementById('alamat_supplier-error').innerHTML ='';
			$.ajax({
          	type:"post",
      		url: '<?php echo $this->baseUrl();?>/supplier/kirimdata',
          	data:{kode_supplier:kode_supplier, nama_supplier:nama_supplier,alamat_supplier:alamat_supplier,no_tlp:no_tlp,no_hp:no_hp,email:email,tipe:tipe,status:status},
          	dataType:'json',
          	success:function(hasil){
			swal({
				title: 'Tambah Supplier Berhasil !',
				text: 'Auto Close...',
				icon: 'success',
				timer: 4000,
				showConfirmButton: false,
				});
			 
                    
          },
          error:function(hasil){
			swal({
					title: 'Tambah Supplier Berhasil !',
					text: 'Auto Close...',
					icon: 'success',
					timer: 4000,
					showConfirmButton: false,
					});   
          		}
         

    	}); 

				} 
 
    }
 
	function isNumber(evt) {
        var iKeyCode = (evt.which) ? evt.which : evt.keyCode
        if (iKeyCode != 46 && iKeyCode > 31 && (iKeyCode < 48 || iKeyCode > 57))
            return false;

        return true;
    } 
</script>