<?php
$mpdf = new \Mpdf\Mpdf([
  'margin_left' => 2,
  'margin_top' => 2,
  'margin_right' => 2,
  'margin_bottom' => 2,
]);
ob_start();
?>
<!DOCTYPE html>
<html>

<head>
  <title>Vapehitz - Print</title>
  <style>
    table {
      border-collapse: collapse;
      width: 100%;
      font-size: 10px;
    }

    td {
      border: 1px solid #000;
      padding: 2px;
    }
  </style>
</head>

<body>
  <div align="center">
    <h2 align="center">List All Devices</h2>
    <table>
      <thead style="background-color: #4ECDC4; color: #fff;">
        <tr>
          <td>Kode</td>
          <td>Merk</td>
          <td>Nama</td>
          <td>Jenis Device</td>
          <td>Stok Pusat</td>
          <td>Stok Retail</td>
          <td>Stok Studio</td>
          <td>Bad Stok</td>
          <td>Berat</td>
          <td>Harga Beli</td>
          <td>Harga Jual Agen</td>
          <td>Harga Jual Retail</td>
          <td>Harga Jual Whs</td>
          <td>Nama Supplier</td>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($this->data as $data) : ?>
          <tr>

            <td><?= $data['kode_device'] ?></td>
            <td><?= $data['merk_device'] ?></td>
            <td><?= $data['nama_device'] ?></td>
            <td><?= $data['jenis_device'] ?></td>
            <td><?= $data['stok_pusat'] ?></td>
            <td><?= $data['stok_retail'] ?></td>
            <td><?= $data['stok_studio'] ?></td>
            <td><?= $data['bad_stock'] ?></td>
            <td><?= $data['berat'] ?></td>
            <td style="text-align: right;"><?= number_format($data['harga_beli'], 0, ',', '.') ?></td>
            <td style="text-align: right;"><?= number_format($data['hj_agen'], 0, ',', '.') ?></td>
            <td style="text-align: right;"><?= number_format($data['hj_retail'], 0, ',', '.') ?></td>
            <td style="text-align: right;"><?= number_format($data['hj_whs'], 0, ',', '.') ?></td>
            <td><?= $this->Device_Service->getdatasupplierid($data['kode_supplier'])[0]['nama_supplier'] ?></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>
</body>

</html>
<?php
$html = ob_get_contents();
ob_end_clean();
$mpdf->WriteHTML(utf8_encode($html));
$mpdf->Output();
?>