<?php

use \PhpOffice\PhpSpreadsheet\Spreadsheet;
use \PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValue('A1', 'Kode');
$sheet->setCellValue('B1', 'Merk');
$sheet->setCellValue('C1', 'Nama');
$sheet->setCellValue('D1', 'Jenis');
$sheet->setCellValue('E1', 'Stok Pusat');
$sheet->setCellValue('F1', 'Stok Retail');
$sheet->setCellValue('G1', 'Stok Studio');
$sheet->setCellValue('H1', 'Bad Stock');
$sheet->setCellValue('I1', 'Berat');
$sheet->setCellValue('J1', 'Harga Beli');
$sheet->setCellValue('K1', 'Harga Jual Agen');
$sheet->setCellValue('L1', 'Harga Jual Ret');
$sheet->setCellValue('M1', 'Harga Jual Whs');
$sheet->setCellValue('N1', 'Nama Supplier');
$sheet->setCellValue('O1', 'Tipe');

$rowNum = 2;

foreach ($this->data as $accessories) {

  $supplier = $this->Accessories_Service->getdatasupplierid($accessories['kode_supplier']);

  $sheet->setCellValue('A' . $rowNum, $accessories['kode_aksesoris']);
  $sheet->setCellValue('B' . $rowNum, $accessories['merk_aksesoris']);
  $sheet->setCellValue('C' . $rowNum, $accessories['nama_aksesoris']);
  $sheet->setCellValue('D' . $rowNum, $accessories['jenis_aksesoris']);
  $sheet->setCellValue('E' . $rowNum, $accessories['stok_pusat']);
  $sheet->setCellValue('F' . $rowNum, $accessories['stok_retail']);
  $sheet->setCellValue('G' . $rowNum, $accessories['stok_studio']);
  $sheet->setCellValue('H' . $rowNum, $accessories['bad_stock']);
  $sheet->setCellValue('I' . $rowNum, $accessories['berat']);
  $sheet->setCellValue('J' . $rowNum, $accessories['harga_beli']);
  $sheet->setCellValue('K' . $rowNum, $accessories['hj_agen']);
  $sheet->setCellValue('L' . $rowNum, $accessories['hj_retail']);
  $sheet->setCellValue('M' . $rowNum, $accessories['hj_whs']);
  $sheet->setCellValue('N' . $rowNum, $supplier[0]['nama_supplier']);
  $sheet->setCellValue('O' . $rowNum, $supplier[0]['tipe']);

  // $spreadsheet->getActiveSheet()->getStyle('B' . $rowNum)->getNumberFormat()
  //   ->setFormatCode('#,##0.00');

  // $total += $sale['total'];

  $rowNum++;
}

$styleArray = array(
  'borders' => array(
    'top' => array(
      'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
    ),
    'bottom' => array(
      'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
    ),
    'right' => array(
      'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
    ),
    'left' => array(
      'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
    ),

  ),
);

$borderRange = "A1:O" . ($rowNum - 1);

$sheet = $sheet->getStyle($borderRange)->applyFromArray($styleArray);

$writer = new Xlsx($spreadsheet);
ob_end_clean();
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment; filename="Data Accessories.xlsx"');
$writer->save("php://output");
