<?php
$mpdf = new \Mpdf\Mpdf([
  'margin_left' => 2,
  'margin_top' => 2,
  'margin_right' => 2,
  'margin_bottom' => 2,
]);
ob_start();
?>
<!DOCTYPE html>
<html>

<head>
  <title>Vapehitz - Print</title>
  <style>
    table {
      border-collapse: collapse;
      width: 100%;
      font-size: 10px;
    }

    td {
      border: 1px solid #000;
      padding: 2px;
    }
  </style>
</head>

<body>
  <div align="center">
    <h2 align="center">Sales By Product Detail</h2>
    <table>
      <thead style="background-color: #4ECDC4; color: #fff;">
        <tr>
          <td>Product</td>
          <td>No.</td>
          <td>Customer</td>
          <td>Date</td>
          <td>Description</td>
          <td>Qty</td>
          <td>Price</td>
          <td>Amount</td>
        </tr>
      </thead>
      <tbody>
        <?php $index = 0; ?>
        <?php $totalForProduct = 0; ?>
        <?php $grandTotal = 0; ?>

        <?php foreach ($this->salesDetail as $sale) : ?>
          <tr>

            <?php if ($index > 0) : ?>
              <?php if ($sale['kode_barang'] !== $this->salesDetail[$index - 1]['kode_barang']) : ?>
                <td><?= $sale['kode_barang'] ?> - <?= $sale['nama_barang'] ?></td>
              <?php else : ?>
                <td></td>
              <?php endif; ?>
            <?php else : ?>
              <td><?= $sale['kode_barang'] ?> - <?= $sale['nama_barang'] ?></td>
            <?php endif; ?>


            <td><?= $sale['no_invoice'] ?></td>

            <td><?= $sale['nama_customer'] ?></td>
            <td><?= date_format(date_create($sale['tgl_invoice']), "d-m-Y") ?></td>
            <td><?= $sale['keterangan'] ?></td>
            <td style="text-align: center;"><?= $sale['qty'] ?></td>
            <td style="text-align: right;"><?= number_format($sale['harga_jual'], 0, ',', '.') ?></td>
            <td style="text-align: right;"><?= number_format($sale['sub_total'], 0, ',', '.') ?></td>
          </tr>

          <?php $totalForProduct += $sale['sub_total'] ?>
          <?php $grandTotal += $sale['sub_total'] ?>

          <?php if ($index < count($this->salesDetail) - 1) : ?>
            <?php if ($sale['nama_barang'] !== $this->salesDetail[$index + 1]['nama_barang']) : ?>
              <tr>
                <td><strong>Total for <?= $sale['nama_barang'] ?></strong></td>
                <td colspan="7" style="text-align: right;"><strong><?= number_format($totalForProduct, 0, ',', '.') ?></strong></td>
              </tr>
              <?php $totalForProduct = 0; ?>
            <?php endif; ?>
          <?php else : ?>
            <tr>
              <td><strong>Total for <?= $sale['nama_barang'] ?></strong></td>
              <td colspan="7" style="text-align: right;"><strong><?= number_format($totalForProduct, 0, ',', '.') ?></strong></td>
            </tr>
            <?php $totalForProduct = 0; ?>
          <?php endif; ?>

          <?php $index++; ?>
        <?php endforeach; ?>

        <tr>
          <td>TOTAL</td>
          <td colspan="7" style="text-align: right;"><strong><?= number_format($grandTotal, 0, ',', '.') ?></strong></td>
        </tr>

      </tbody>
    </table>
  </div>
</body>

</html>
<?php
$html = ob_get_contents();
ob_end_clean();
$mpdf->WriteHTML(utf8_encode($html));
$mpdf->Output();
?>