<?php

use \PhpOffice\PhpSpreadsheet\Spreadsheet;
use \PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValue('A1', 'Customer');
$sheet->setCellValue('B1', 'Total');

$index = 0;
$total = 0;
$rowNum = 2;

foreach ($this->totalPurchases as $purchase) {

  $sheet->setCellValue('A' . $rowNum, $purchase['nama_supplier']);
  $sheet->setCellValue('B' . $rowNum, $purchase['total']);

  $spreadsheet->getActiveSheet()->getStyle('B' . $rowNum)->getNumberFormat()
    ->setFormatCode('#,##0.00');

  $total += $purchase['total'];

  $rowNum++;
  $index++;
}

$sheet->setCellValue('A' . $rowNum, 'Total');
$sheet->setCellValue('B' . $rowNum, $total);

$spreadsheet->getActiveSheet()->getStyle('B' . $rowNum)->getNumberFormat()
  ->setFormatCode('#,##0.00');

// $styleArray = array(
//   'borders' => array(
//     'top' => array(
//       'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
//     ),
//     'bottom' => array(
//       'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
//     ),
//     'right' => array(
//       'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
//     ),
//     'left' => array(
//       'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
//     ),

//   ),
// );

// $borderRange = "A1:B" . ($rowNum);

// $sheet = $sheet->getStyle($borderRange)->applyFromArray($styleArray);

$writer = new Xlsx($spreadsheet);
ob_end_clean();
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment; filename="Purchases By Supplier Summary.xlsx"');
$writer->save("php://output");
