<?php
$mpdf = new \Mpdf\Mpdf([
  'margin_left' => 2,
  'margin_top' => 2,
  'margin_right' => 2,
  'margin_bottom' => 2,
]);
ob_start();
?>
<!DOCTYPE html>
<html>

<head>
  <title>Vapehitz - Print</title>
  <style>
    table {
      border-collapse: collapse;
      width: 100%;
      font-size: 10px;
    }

    td {
      border: 1px solid #000;
      padding: 2px;
    }
  </style>
</head>

<body>
  <div align="center">
    <h2 align="center">Purchases By Supplier Detail</h2>
    <table>
      <thead style="background-color: #4ECDC4; color: #fff;">
        <tr>
          <td>Supplier</td>
          <td>No.</td>
          <td>Product</td>
          <td>Date</td>
          <td>Description</td>
          <td>Qty</td>
          <td>Price</td>
          <td>Amount</td>
        </tr>
      </thead>
      <tbody>
        <?php $index = 0; ?>
        <?php $totalForSupplier = 0; ?>
        <?php $totalOrder = 0; ?>

        <?php foreach ($this->purchasesDetail as $purchase) : ?>
          <tr>

            <?php if ($index > 0) : ?>
              <?php if ($purchase['kode_supplier'] !== $this->purchasesDetail[$index - 1]['kode_supplier']) : ?>
                <td><?= $purchase['nama_supplier'] ?></td>
              <?php else : ?>
                <td></td>
              <?php endif; ?>
            <?php else : ?>
              <td><?= $purchase['nama_supplier'] ?></td>
            <?php endif; ?>

            <?php if ($index > 0) : ?>
              <?php if ($purchase['no_order'] !== $this->purchasesDetail[$index - 1]['no_order']) : ?>
                <td><?= $purchase['no_order'] ?></td>
              <?php else : ?>
                <td></td>
              <?php endif; ?>
            <?php else : ?>
              <td><?= $purchase['no_order'] ?></td>
            <?php endif; ?>

            <td><?= $purchase['nama_barang'] ?></td>
            <td><?= date_format(date_create($purchase['tgl_order']), "d-m-Y") ?></td>
            <td><?= $purchase['keterangan'] ?></td>
            <td style="text-align: center;"><?= $purchase['qty'] ?></td>
            <td style="text-align: right;"><?= number_format($purchase['harga_beli'], 0, ',', '.') ?></td>
            <td style="text-align: right;"><?= number_format($purchase['sub_total'], 0, ',', '.') ?></td>
          </tr>


          <?php if ($index < count($this->purchasesDetail) - 1) : ?>
            <?php if ($purchase['no_order'] !== $this->purchasesDetail[$index + 1]['no_order']) : ?>
              <tr>
                <td></td>
                <td><strong>Shipping Cost</strong></td>
                <td colspan="6" style="text-align: right;"><strong><?= number_format($purchase['biaya_kirim'], 0, ',', '.') ?></strong></td>
              </tr>
              <tr>
                <td></td>
                <td><strong>Discount</strong></td>
                <?php
                if ($purchase['jenis_diskon'] == 'persen') {
                  $purchase['diskon'] = $purchase['total_biaya'] * ($purchase['diskon'] / 100);
                }
                ?>
                <td colspan="6" style="text-align: right;"><strong><?= number_format($purchase['diskon'], 0, ',', '.') ?></strong></td>
              </tr>
              <tr>
                <td></td>
                <td><strong>Total Order</strong></td>
                <td colspan="6" style="text-align: right;"><strong><?= number_format($purchase['net_total'], 0, ',', '.') ?></strong></td>
              </tr>
              <?php $totalForSupplier += $purchase['net_total'] ?>
            <?php endif; ?>
          <?php else : ?>
            <tr>
              <td></td>
              <td><strong>Shipping Cost</strong></td>
              <td colspan="6" style="text-align: right;"><strong><?= number_format($purchase['biaya_kirim'], 0, ',', '.') ?></strong></td>
            </tr>
            <tr>
              <td></td>
              <td><strong>Discount</strong></td>
              <?php
              if ($purchase['jenis_diskon'] == 'persen') {
                $purchase['diskon'] = $purchase['total_biaya'] * ($purchase['diskon'] / 100);
              }
              ?>
              <td colspan="6" style="text-align: right;"><strong><?= number_format($purchase['diskon'], 0, ',', '.') ?></strong></td>
            </tr>
            <tr>
              <td></td>
              <td><strong>Total Order</strong></td>
              <td colspan="6" style="text-align: right;"><strong><?= number_format($purchase['net_total'], 0, ',', '.') ?></strong></td>
            </tr>
            <?php $totalForSupplier += $purchase['net_total'] ?>
          <?php endif; ?>

          <?php if ($index < count($this->purchasesDetail) - 1) : ?>
            <?php if ($purchase['kode_supplier'] !== $this->purchasesDetail[$index + 1]['kode_supplier']) : ?>
              <tr>
                <td><strong>Total for <?= $purchase['nama_supplier'] ?></strong></td>
                <td colspan="7" style="text-align: right;"><strong><?= number_format($totalForSupplier, 0, ',', '.') ?></strong></td>
              </tr>
              <?php $totalForSupplier = 0; ?>
            <?php endif; ?>
          <?php else : ?>
            <tr>
              <td><strong>Total for <?= $purchase['nama_supplier'] ?></strong></td>
              <td colspan="7" style="text-align: right;"><strong><?= number_format($totalForSupplier, 0, ',', '.') ?></strong></td>
            </tr>
            <?php $totalForSupplier = 0; ?>
          <?php endif; ?>

          <?php $index++; ?>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>
</body>

</html>
<?php
$html = ob_get_contents();
ob_end_clean();
$mpdf->WriteHTML(utf8_encode($html));
$mpdf->Output();
?>