<?php

use \PhpOffice\PhpSpreadsheet\Spreadsheet;
use \PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValue('A1', 'Product');
$sheet->setCellValue('B1', 'No.');
$sheet->setCellValue('C1', 'Created By');
$sheet->setCellValue('D1', 'Customer');
$sheet->setCellValue('E1', 'Date');
$sheet->setCellValue('F1', 'Description');
$sheet->setCellValue('G1', 'Qty');
$sheet->setCellValue('H1', 'Price');
$sheet->setCellValue('I1', 'Amount');

$index = 0;
$totalForProduct = 0;
$rowNum = 2;
$grandTotal = 0;

foreach ($this->purchasesDetail as $purchase) {
  if ($index > 0) {
    if ($purchase['kode_barang'] !== $this->purchasesDetail[$index - 1]['kode_barang']) {
      $sheet->setCellValue('A' . $rowNum, $purchase['kode_barang'] . ' - ' . $purchase['nama_barang']);
    } else {
      $sheet->setCellValue('A' . $rowNum, '');
    }
  } else {
    $sheet->setCellValue('A' . $rowNum, $purchase['kode_barang'] . ' - ' . $purchase['nama_barang']);
  }

  // if ($index > 0) {
  //   if ($purchase['no_order'] !== $this->purchasesDetail[$index - 1]['no_order']) {
  //     $sheet->setCellValue('B' . $rowNum, $purchase['no_order']);
  //     $sheet->setCellValue('C' . $rowNum, $purchase['created_by']);
  //   } else {
  //     $sheet->setCellValue('B' . $rowNum, '');
  //   }
  // } else {
  //   $sheet->setCellValue('B' . $rowNum, $purchase['no_order']);
  //   $sheet->setCellValue('C' . $rowNum, $purchase['created_by']);
  // }

  $sheet->setCellValue('B' . $rowNum, $purchase['no_order']);
  $sheet->setCellValue('C' . $rowNum, $purchase['created_by']);
  $sheet->setCellValue('D' . $rowNum, $purchase['nama_supplier']);
  $sheet->setCellValue('E' . $rowNum, date_format(date_create($purchase['tgl_order']), "d-m-Y"));
  $sheet->setCellValue('F' . $rowNum, $purchase['keterangan']);
  $sheet->setCellValue('G' . $rowNum, $purchase['qty']);
  $sheet->setCellValue('H' . $rowNum, $purchase['harga_beli']);

  $spreadsheet->getActiveSheet()->getStyle('H' . $rowNum)->getNumberFormat()
    ->setFormatCode('#,##0.00');

  $sheet->setCellValue('I' . $rowNum, $purchase['sub_total']);

  $spreadsheet->getActiveSheet()->getStyle('I' . $rowNum)->getNumberFormat()
    ->setFormatCode('#,##0.00');

  $totalForProduct += $purchase['sub_total'];
  $grandTotal += $purchase['sub_total'];

  $rowNum++;

  // if ($index < count($this->purchasesDetail) - 1) {

  //   if ($purchase['nama_barang'] !== $this->purchasesDetail[$index + 1]['nama_barang']) {
  //     $sheet->setCellValue('A' . $rowNum, '');
  //     $sheet->setCellValue('B' . $rowNum, 'Discount');

  //     if ($purchase['jenis_diskon'] == 'persen') {
  //       $purchase['diskon'] = $purchase['total_biaya'] * ($purchase['diskon'] / 100);
  //     }

  //     $sheet->setCellValue('C' . $rowNum, $purchase['diskon']);

  //     $spreadsheet->getActiveSheet()->getStyle('C' . $rowNum)->getNumberFormat()
  //       ->setFormatCode('#,##0.00');

  //     $spreadsheet->getActiveSheet()->mergeCells("C$rowNum:I$rowNum");

  //     $rowNum++;

  //     $sheet->setCellValue('B' . $rowNum, 'Total Invoice');
  //     $sheet->setCellValue('C' . $rowNum, $purchase['salecentral_sub_total']);

  //     $spreadsheet->getActiveSheet()->getStyle('C' . $rowNum)->getNumberFormat()
  //       ->setFormatCode('#,##0.00');

  //     $spreadsheet->getActiveSheet()->mergeCells("C$rowNum:I$rowNum");

  //     $totalForCustomer += $purchase['salecentral_sub_total'];
  //   }
  // } else {

  //   $sheet->setCellValue('B' . $rowNum, 'Discount');

  //   if ($purchase['jenis_diskon'] == 'persen') {
  //     $purchase['diskon'] = $purchase['total_biaya'] * ($purchase['diskon'] / 100);
  //   }

  //   $sheet->setCellValue('C' . $rowNum, $purchase['diskon']);

  //   $spreadsheet->getActiveSheet()->getStyle('C' . $rowNum)->getNumberFormat()
  //     ->setFormatCode('#,##0.00');

  //   $spreadsheet->getActiveSheet()->mergeCells("C$rowNum:I$rowNum");

  //   $rowNum++;

  //   $sheet->setCellValue('B' . $rowNum, 'Total Invoice');
  //   $sheet->setCellValue('C' . $rowNum, $purchase['salecentral_sub_total']);

  //   $spreadsheet->getActiveSheet()->getStyle('C' . $rowNum)->getNumberFormat()
  //     ->setFormatCode('#,##0.00');

  //   $spreadsheet->getActiveSheet()->mergeCells("C$rowNum:I$rowNum");

  //   $totalForCustomer += $purchase['salecentral_sub_total'];

  //   $rowNum++;
  // }

  // $grandTotal += $totalForCustomer;

  if ($index < count($this->purchasesDetail) - 1) {
    if ($purchase['nama_barang'] !== $this->purchasesDetail[$index + 1]['nama_barang']) {
      $sheet->setCellValue('A' . $rowNum, 'Total for ' . $purchase['nama_barang']);
      $sheet->setCellValue('B' . $rowNum, $totalForProduct);

      $spreadsheet->getActiveSheet()->getStyle('B' . $rowNum)->getNumberFormat()
        ->setFormatCode('#,##0.00');

      $spreadsheet->getActiveSheet()->mergeCells("B$rowNum:I$rowNum");

      $totalForProduct = 0;
    }
  } else {
    $sheet->setCellValue('A' . $rowNum, 'Total for ' . $purchase['nama_barang']);
    $sheet->setCellValue('B' . $rowNum, $totalForProduct);

    $spreadsheet->getActiveSheet()->getStyle('B' . $rowNum)->getNumberFormat()
      ->setFormatCode('#,##0.00');

    $spreadsheet->getActiveSheet()->mergeCells("B$rowNum:I$rowNum");

    $totalForProduct = 0;
  }

  $rowNum++;
  $index++;
}

$sheet->setCellValue('A' . $rowNum, 'TOTAL');
$sheet->setCellValue('I' . $rowNum, $grandTotal);

$spreadsheet->getActiveSheet()->getStyle('I' . $rowNum)->getNumberFormat()
  ->setFormatCode('#,##0.00');

// $styleArray = array(
//   'borders' => array(
//     'top' => array(
//       'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
//     ),
//     'bottom' => array(
//       'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
//     ),
//     'right' => array(
//       'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
//     ),
//     'left' => array(
//       'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
//     ),

//   ),
// );

// $borderRange = "A1:H" . ($rowNum - 1);

// $sheet = $sheet->getStyle($borderRange)->applyFromArray($styleArray);

$writer = new Xlsx($spreadsheet);
ob_end_clean();
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment; filename="purchasesbyproductdetail.xlsx"');
$writer->save("php://output");
$writer->save('Purchases By Product Detail.xlsx');
